# Docker environment configuration
spring:
  application:
    name: saferoute-api-gateway
  
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      database: 0
  
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:3000
          predicates:
            - Path=/api/users/**
          filters:
            - name: RateLimiter
              args:
                "[redis-rate-limiter.replenish-rate]": 10
                "[redis-rate-limiter.burst-capacity]": 20
                "[redis-rate-limiter.requested-tokens]": 1
            - name: CircuitBreaker
              args:
                name: user-service-cb
                fallback-uri: forward:/fallback/user-service
        
        - id: order-service
          uri: http://order-service:3000
          predicates:
            - Path=/api/orders/**
          filters:
            - name: RateLimiter
              args:
                "[redis-rate-limiter.replenish-rate]": 5
                "[redis-rate-limiter.burst-capacity]": 10
                "[redis-rate-limiter.requested-tokens]": 1
            - name: CircuitBreaker
              args:
                name: order-service-cb
                fallback-uri: forward:/fallback/order-service
        
        - id: product-service
          uri: http://product-service:3000
          predicates:
            - Path=/api/products/**
          filters:
            - name: RateLimiter
              args:
                "[redis-rate-limiter.replenish-rate]": 15
                "[redis-rate-limiter.burst-capacity]": 30
                "[redis-rate-limiter.requested-tokens]": 1
            - name: CircuitBreaker
              args:
                name: product-service-cb
                fallback-uri: forward:/fallback/product-service

logging:
  level:
    "[org.springframework.cloud.gateway]": INFO
    "[com.saferoute]": INFO
